#!/usr/bin/env python3
"""Export park graph and ride static data for the C++ simulator."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

import config  # noqa: E402
from park_graph import build_graph, get_park_graph  # noqa: E402


def _fmt_int_row(values: list[int]) -> str:
    return "{" + ", ".join(str(v) for v in values) + "}"


def _fmt_nested_int_row(values: list[int]) -> str:
    """Double-brace row for std::array<std::array<...>> aggregate init."""
    return "{{" + ", ".join(str(v) for v in values) + "}}"


def _fmt_float_row(values: list[float]) -> str:
    return "{" + ", ".join(repr(float(v)) for v in values) + "}"


def main() -> None:
    graph = build_graph()
    park = get_park_graph()
    node_ids = sorted(graph.node_coords.keys())
    num_nodes = len(node_ids)

    walk_rows = []
    for i in range(num_nodes):
        walk_rows.append([graph.walk_time_sec[i][j] for j in range(num_nodes)])

    walk_to_rides = park.base_walk_to_rides.tolist()
    node_idx_to_ride = park.node_idx_to_ride.tolist()
    ride_node_idx = park.ride_node_idx.tolist()

    idle_neighbors: list[list[int]] = []
    for node_id in node_ids:
        idle_neighbors.append(park.neighbors_within_hops(node_id, config.IDLE_MAX_HOPS))

    ride_capacity = []
    ride_duration = []
    ride_breakdown = []
    for cfg in config.get_ride_configs():
        ride_capacity.append(cfg["capacity_per_sec"])
        ride_duration.append(cfg["duration_sec"])
        ride_breakdown.append(cfg["breakdown_prob_sec"])

    out_dir = ROOT / "native" / "generated"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "graph_data.hpp"

    lines = [
        "#pragma once",
        "// Auto-generated by tools/export_native_data.py — do not edit.",
        "#include <array>",
        "#include <cstddef>",
        "#include <cstdint>",
        "#include <vector>",
        "",
        "namespace park {",
        "namespace graph_data {",
        "",
        f"inline constexpr int kNumRides = {config.NUM_RIDES};",
        f"inline constexpr int kNumNodes = {num_nodes};",
        f"inline constexpr int kEntranceNodeIdx = {int(park.entrance_node_idx)};",
        "",
        f"inline constexpr std::array<double, kNumRides> kRideCapacityPerSec = {_fmt_float_row(ride_capacity)};",
        f"inline constexpr std::array<int, kNumRides> kRideDurationSec = {_fmt_int_row(ride_duration)};",
        f"inline constexpr std::array<double, kNumRides> kRideBreakdownProbSec = {_fmt_float_row(ride_breakdown)};",
        f"inline constexpr std::array<int, kNumRides> kRideNodeIdx = {_fmt_int_row(ride_node_idx)};",
        "",
        f"inline constexpr std::array<int16_t, kNumNodes> kNodeIdxToRide = {_fmt_int_row(node_idx_to_ride)};",
        "",
        "inline constexpr std::array<std::array<int, kNumNodes>, kNumNodes> kBaseWalkMatrix = {{",
    ]
    for row in walk_rows:
        lines.append(f"    {_fmt_nested_int_row(row)},")
    lines.append("}};")
    lines.append("")
    lines.append(
        "inline constexpr std::array<std::array<int, kNumRides>, kNumNodes> kBaseWalkToRides = {{"
    )
    for row in walk_to_rides:
        lines.append(f"    {_fmt_nested_int_row(row)},")
    lines.append("}};")
    lines.append("")
    lines.append("inline const std::vector<std::vector<int>> kIdleNeighborNodeIdx = {")

    idx_of = {nid: i for i, nid in enumerate(node_ids)}
    for node_id in node_ids:
        idxs = [idx_of[n] for n in idle_neighbors[node_ids.index(node_id)] if n in idx_of]
        if idxs:
            lines.append(f"    {_fmt_int_row(idxs)},")
        else:
            lines.append("    {},")

    lines.extend(
        [
            "};",
            "",
            "}  // namespace graph_data",
            "}  // namespace park",
            "",
        ]
    )

    out_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"Wrote {out_path}")


if __name__ == "__main__":
    main()
